# Generated by Django 5.2 on 2025-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_flight_image_url_hotel_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
