# Generated by Django 5.2 on 2025-05-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activity_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('adventure', 'Adventure'), ('culture', 'Culture'), ('wellness', 'Wellness'), ('sports', 'Sports'), ('food', 'Food & Dining'), ('shopping', 'Shopping'), ('nightlife', 'Nightlife'), ('nature', 'Nature & Wildlife'), ('museum', 'Museums & Art'), ('entertainment', 'Entertainment')], default='culture', max_length=20),
        ),
        migrations.AddField(
            model_name='matchticket',
            name='match_type',
            field=models.CharField(choices=[('world_cup', 'World Cup'), ('can', 'CAN'), ('friendly', 'Friendly'), ('league', 'League')], default='friendly', max_length=20),
        ),
    ]
