# Generated by Django 5.2 on 2025-05-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_activity_activity_type_matchticket_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('TOUR', 'Tour'), ('WORKSHOP', 'Workshop'), ('EXHIBITION', 'Exhibition'), ('CONCERT', 'Concert'), ('FAN_ZONE', 'Fan Zone')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='match_ticket',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.AlterField(
            model_name='matchticket',
            name='match_type',
            field=models.CharField(choices=[('GROUP_STAGE', 'Group Stage'), ('ROUND_OF_16', 'Round of 16'), ('QUARTER_FINALS', 'Quarter Finals'), ('SEMI_FINALS', 'Semi Finals'), ('FINAL', 'Final')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ManyToManyField(blank=True, to='core.activity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ManyToManyField(blank=True, to='core.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='core.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='match_ticket',
            field=models.ManyToManyField(blank=True, to='core.matchticket'),
        ),
    ]
