# Generated by Django 5.2 on 2025-05-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flight_airline_package_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('MUSEUM', 'Museum'), ('TRAVEL', 'Travel'), ('SPORT', 'Sport'), ('ENTERTAINMENT', 'Entertainment'), ('CULTURE', 'Culture'), ('SHOPPING', 'Shopping'), ('FOOD', 'Food & Dining'), ('NIGHTLIFE', 'Nightlife'), ('TOUR', 'Tour'), ('WORKSHOP', 'Workshop'), ('EXHIBITION', 'Exhibition'), ('CONCERT', 'Concert'), ('FAN_ZONE', 'Fan Zone')], max_length=20),
        ),
    ]
