# Generated by Django 5.2 on 2025-05-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
